import { type ButtonHTMLAttributes, type ChangeEvent, type InputHTMLAttributes, type ReactNode, type SelectHTMLAttributes } from 'react';
import { AlertCircle, Check, Loader2, Plus, RefreshCw, X } from 'lucide-react';

export function Button({ children, variant = 'primary', size, className = '', ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { variant?: 'primary' | 'secondary' | 'ghost' | 'danger'; size?: 'sm' | 'md'; children: ReactNode }) {
  const styles = { primary: 'bg-[hsl(var(--primary))] text-[hsl(var(--primary-foreground))] hover:opacity-90', secondary: 'bg-[hsl(var(--secondary))] text-[hsl(var(--secondary-foreground))] hover:bg-[hsl(var(--accent)/.32)]', ghost: 'border border-[hsl(var(--border))] bg-[hsl(var(--card))] text-[hsl(var(--foreground))] hover:bg-[hsl(var(--muted))]', danger: 'bg-[hsl(var(--destructive))] text-[hsl(var(--destructive-foreground))] hover:opacity-90' };
  const sizing = size === 'sm' ? 'min-h-8 px-3 text-[12px]' : 'min-h-10 px-4 text-[13px]';
  return <button {...props} className={`inline-flex items-center justify-center gap-2 rounded-xl font-semibold transition active:scale-[.98] disabled:cursor-not-allowed disabled:opacity-50 ${sizing} ${styles[variant]} ${className}`}>{children}</button>;
}
export function IconButton({ label, children, ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { label: string; children: ReactNode }) { return <button {...props} aria-label={label} className={`rounded-xl p-2 text-[hsl(var(--muted-foreground))] transition hover:bg-[hsl(var(--muted))] hover:text-[hsl(var(--foreground))] ${props.className || ''}`}>{children}</button>; }
export function Panel({ children, className = '' }: { children: ReactNode; className?: string }) { return <section className={`rounded-2xl border border-[hsl(var(--card-border))] bg-[hsl(var(--card))] shadow-[var(--shadow-sm)] ${className}`}>{children}</section>; }
export function PanelTitle({ eyebrow, title, action }: { eyebrow?: string; title: string; action?: ReactNode }) { return <div className="flex items-start justify-between gap-3 px-4 pt-4 sm:px-5 sm:pt-5"><div>{eyebrow && <div className="mb-1 font-mono text-[9px] uppercase tracking-[.17em] text-[hsl(var(--muted-foreground))]">{eyebrow}</div>}<h2 className="font-[family-name:var(--app-font-serif)] text-[17px] font-bold tracking-[-.02em]">{title}</h2></div>{action}</div>; }
export function Stat({ label, value, note, tone = 'plain' }: { label: string; value: ReactNode; note?: ReactNode; tone?: 'plain' | 'green' | 'gold' | 'red' }) { const t = { plain: 'text-[hsl(var(--foreground))]', green: 'text-[hsl(var(--primary))]', gold: 'text-[hsl(var(--accent))]', red: 'text-[hsl(var(--destructive))]' }; return <div><div className="mb-1 text-[10px] font-semibold uppercase tracking-[.12em] text-[hsl(var(--muted-foreground))]">{label}</div><div className={`font-[family-name:var(--app-font-serif)] text-[25px] font-bold tracking-[-.04em] ${t[tone]}`}>{value}</div>{note && <div className="mt-1 text-[11px] text-[hsl(var(--muted-foreground))]">{note}</div>}</div>; }
export function Badge({ children, tone = 'neutral' }: { children: ReactNode; tone?: 'neutral' | 'green' | 'gold' | 'red' | 'blue' }) { const c = { neutral: 'bg-[hsl(var(--muted))] text-[hsl(var(--muted-foreground))]', green: 'bg-[#dbeedc] text-[#27633e]', gold: 'bg-[#f9e6ae] text-[#795811]', red: 'bg-[#f5d8d3] text-[#984336]', blue: 'bg-[#d8e9ed] text-[#2d6471]' }; return <span className={`inline-flex items-center rounded-full px-2 py-1 text-[10px] font-bold capitalize ${c[tone]}`}>{children}</span>; }
export function Meter({ value, color = 'primary' }: { value: number; color?: 'primary' | 'gold' | 'red' }) { return <div className="h-1.5 overflow-hidden rounded-full bg-[hsl(var(--muted))]"><div className={`h-full rounded-full transition-all duration-500 ${color === 'gold' ? 'bg-[hsl(var(--accent))]' : color === 'red' ? 'bg-[hsl(var(--destructive))]' : 'bg-[hsl(var(--primary))]'}`} style={{ width: `${Math.min(100, Math.max(0, value))}%` }} /></div>; }
export function Loading({ rows = 4 }: { rows?: number }) { return <div className="space-y-3" data-testid="status-loading">{Array.from({ length: rows }).map((_, i) => <div key={i} className="h-12 animate-pulse rounded-xl bg-[hsl(var(--muted))]" />)}</div>; }
export function ErrorState({ onRetry }: { onRetry?: () => void }) { return <div className="flex flex-col items-center justify-center rounded-2xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-10 text-center" data-testid="status-error"><AlertCircle className="mb-3 text-[hsl(var(--destructive))]" /><p className="font-semibold">The record book could not be opened.</p><p className="mt-1 text-sm text-[hsl(var(--muted-foreground))]">Check your connection and try again.</p>{onRetry && <Button variant="ghost" className="mt-4" onClick={onRetry}><RefreshCw size={15} /> Try again</Button>}</div>; }
export function EmptyState({ title, detail, onAdd, action, icon: Icon }: { title: string; detail: string; onAdd?: () => void; action?: ReactNode; icon?: React.ComponentType<{ size?: number; className?: string }> }) { return <div className="rounded-2xl border border-dashed border-[hsl(var(--border))] bg-[hsl(var(--card)/.55)] p-10 text-center" data-testid="status-empty"><div className="mx-auto mb-3 flex h-10 w-10 items-center justify-center rounded-full bg-[hsl(var(--secondary))] text-[hsl(var(--primary))]">{Icon ? <Icon size={18} /> : <Plus size={18} />}</div><p className="font-semibold">{title}</p><p className="mx-auto mt-1 max-w-sm text-sm text-[hsl(var(--muted-foreground))]">{detail}</p>{action || (onAdd && <Button onClick={onAdd} className="mt-5"><Plus size={15} /> Add first record</Button>)}</div>; }
export function Modal({ title, onClose, children, open = true }: { title: string; onClose: () => void; children: ReactNode; open?: boolean }) { if (!open) return null; return <div className="fixed inset-0 z-50 flex items-end justify-center bg-[hsl(var(--foreground)/.35)] p-0 sm:items-center sm:p-5"><div className="max-h-[92dvh] w-full overflow-auto rounded-t-3xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-5 shadow-[var(--shadow-md)] sm:max-w-lg sm:rounded-3xl"><div className="mb-5 flex items-center justify-between"><h2 className="font-[family-name:var(--app-font-serif)] text-xl font-bold">{title}</h2><IconButton label="Close dialog" onClick={onClose}><X size={19} /></IconButton></div>{children}</div></div>; }
export function FormField({ label, name, type = 'text', placeholder, required = false, value, onChange, ...props }: Omit<InputHTMLAttributes<HTMLInputElement>, 'name'> & { label: string; name?: string; value?: string | number; onChange?: (event: ChangeEvent<HTMLInputElement>) => void; required?: boolean }) { return <label className="block"><span className="mb-1.5 block text-[11px] font-semibold text-[hsl(var(--muted-foreground))]">{label}{required && ' *'}</span><input data-testid={name ? `input-${name}` : undefined} name={name} type={type} placeholder={placeholder} required={required} value={value} onChange={onChange} {...props} className={`h-10 w-full rounded-xl border border-[hsl(var(--input))] bg-[hsl(var(--background))] px-3 text-sm outline-none transition focus:border-[hsl(var(--primary))] focus:ring-2 focus:ring-[hsl(var(--primary)/.16)] ${props.className || ''}`} /></label>; }
type SelectOption = string | { value: string; label: string };
export function SelectField({ label, name, options, required = false, value, onChange, ...props }: Omit<SelectHTMLAttributes<HTMLSelectElement>, 'name'> & { label: string; name?: string; options: SelectOption[]; value?: string; onChange?: (event: ChangeEvent<HTMLSelectElement>) => void; required?: boolean }) { return <label className="block"><span className="mb-1.5 block text-[11px] font-semibold text-[hsl(var(--muted-foreground))]">{label}{required && ' *'}</span><select data-testid={name ? `select-${name}` : undefined} name={name} required={required} value={value} onChange={onChange} {...props} className={`h-10 w-full rounded-xl border border-[hsl(var(--input))] bg-[hsl(var(--background))] px-3 text-sm outline-none focus:border-[hsl(var(--primary))] ${props.className || ''}`}>{options.map(o => typeof o === 'string' ? <option key={o} value={o}>{o}</option> : <option key={o.value} value={o.value}>{o.label}</option>)}</select></label>; }
export function SaveButton({ pending, children = 'Save record' }: { pending?: boolean; children?: ReactNode }) { return <Button data-testid="button-save-record" type="submit" disabled={pending}>{pending ? <><Loader2 size={15} className="animate-spin" /> Saving…</> : <><Check size={15} />{children}</>}</Button>; }
