import { useEffect, useState, type FormEvent } from "react";
import { CircleDollarSign, Droplets, Fish, Leaf, Plus, RefreshCw, Trash2, Tractor, TreePine, Wheat, Wrench } from "lucide-react";
import { Button, EmptyState, ErrorState, Loading, Modal, Panel, PanelTitle, SelectField, Stat } from "@/components/ui-kit";
import { PageHeading } from "@/components/farm-shell";

type RecordItem = { id:number; recordType:string; name:string; status:string; farmUnit:string; recordDate:string|null; data:Record<string,unknown>; createdAt:string; updatedAt:string };
type Field = { key:string; label:string; type?:"text"|"number"|"date"; placeholder?:string };
type Module = { type:string; label:string; description:string; icon:React.ElementType; fields:Field[] };

const modules:Module[] = [
 {type:"pig",label:"Pigs",description:"Breeding, growing, health and sales records.",icon:Tractor,fields:[{key:"pigId",label:"Pig ID"},{key:"sex",label:"Sex"},{key:"breed",label:"Breed"},{key:"birthDate",label:"Birth date",type:"date"},{key:"weightKg",label:"Weight (kg)",type:"number"},{key:"pen",label:"Pen"},{key:"health",label:"Health"},{key:"notes",label:"Notes"}]},
 {type:"fish",label:"Fish",description:"Tanks, stocking, growth and harvest records.",icon:Fish,fields:[{key:"tankId",label:"Tank ID"},{key:"dimensions",label:"Dimensions",placeholder:"10m × 10m"},{key:"species",label:"Species"},{key:"stockingDate",label:"Stocking date",type:"date"},{key:"numberStocked",label:"Number stocked",type:"number"},{key:"currentNumber",label:"Current number",type:"number"},{key:"averageWeightKg",label:"Average weight (kg)",type:"number"},{key:"notes",label:"Notes"}]},
 {type:"fish_water_quality",label:"Fish water",description:"Manual water-quality readings ready for sensors.",icon:Droplets,fields:[{key:"tank",label:"Tank"},{key:"temperatureC",label:"Temperature (°C)",type:"number"},{key:"ph",label:"pH",type:"number"},{key:"dissolvedOxygen",label:"Dissolved oxygen",type:"number"},{key:"ammonia",label:"Ammonia",type:"number"},{key:"waterLevel",label:"Water level"},{key:"clarity",label:"Clarity"},{key:"notes",label:"Notes"}]},
 {type:"field",label:"Fields",description:"Field/plot register for crop production.",icon:Wheat,fields:[{key:"fieldId",label:"Field ID"},{key:"area",label:"Area",type:"number"},{key:"unit",label:"Unit",placeholder:"ha / m²"},{key:"soilType",label:"Soil type"},{key:"irrigation",label:"Irrigation"},{key:"currentCrop",label:"Current crop"},{key:"location",label:"GPS/location"}]},
 {type:"crop",label:"Crop cycles",description:"Planting, inputs, harvest, yield and profitability.",icon:Leaf,fields:[{key:"crop",label:"Crop"},{key:"variety",label:"Variety"},{key:"field",label:"Field"},{key:"plantingDate",label:"Planting date",type:"date"},{key:"expectedHarvestDate",label:"Expected harvest",type:"date"},{key:"seedQuantity",label:"Seed quantity",type:"number"},{key:"inputCost",label:"Input cost",type:"number"},{key:"harvestQuantity",label:"Harvest quantity",type:"number"},{key:"harvestUnit",label:"Harvest unit"}]},
 {type:"crop_activity",label:"Crop activities",description:"Preparation, planting, irrigation, weeding, scouting and harvest.",icon:Leaf,fields:[{key:"activity",label:"Activity"},{key:"field",label:"Field"},{key:"crop",label:"Crop"},{key:"operator",label:"Operator"},{key:"notes",label:"Notes"}]},
 {type:"home_garden",label:"Home garden",description:"Household food production.",icon:Wheat,fields:[{key:"crop",label:"Crop"},{key:"area",label:"Area",type:"number"},{key:"quantityPlanted",label:"Quantity planted",type:"number"},{key:"harvest",label:"Harvest",type:"number"},{key:"householdConsumption",label:"Household consumption",type:"number"},{key:"quantitySold",label:"Quantity sold",type:"number"},{key:"notes",label:"Notes"}]},
 {type:"garden_bed",label:"Commercial garden",description:"Vegetable beds and production economics.",icon:Wheat,fields:[{key:"bed",label:"Bed"},{key:"crop",label:"Crop"},{key:"variety",label:"Variety"},{key:"dimensions",label:"Dimensions",placeholder:"100m × 1.5m"},{key:"plantingDate",label:"Planting date",type:"date"},{key:"inputCost",label:"Input cost",type:"number"},{key:"harvest",label:"Harvest",type:"number"}]},
 {type:"greenhouse",label:"Greenhouse",description:"Plan future protected production without inventing activity.",icon:Leaf,fields:[{key:"dimensions",label:"Dimensions"},{key:"crop",label:"Crop"},{key:"variety",label:"Variety"},{key:"plantingDate",label:"Planting date",type:"date"},{key:"plants",label:"Plants",type:"number"},{key:"temperature",label:"Temperature"},{key:"humidity",label:"Humidity"}]},
 {type:"orchard_tree",label:"Orchard",description:"Tree register and production records.",icon:TreePine,fields:[{key:"treeId",label:"Tree ID"},{key:"species",label:"Species"},{key:"variety",label:"Variety"},{key:"plantingDate",label:"Planting date",type:"date"},{key:"location",label:"Location"},{key:"fruitProduction",label:"Production",type:"number"},{key:"notes",label:"Notes"}]},
 {type:"water_tank",label:"Water tanks",description:"Storage capacity and current water level.",icon:Droplets,fields:[{key:"capacityLitres",label:"Capacity (L)",type:"number"},{key:"currentLitres",label:"Current level (L)",type:"number"},{key:"source",label:"Water source"},{key:"notes",label:"Notes"}]},
 {type:"water_usage",label:"Water usage",description:"Irrigation, livestock, fish and household usage.",icon:Droplets,fields:[{key:"usageType",label:"Usage type"},{key:"litres",label:"Litres",type:"number"},{key:"source",label:"Source"},{key:"operator",label:"Operator"},{key:"notes",label:"Notes"}]},
 {type:"irrigation",label:"Irrigation",description:"Manual irrigation records ready for automation.",icon:Droplets,fields:[{key:"target",label:"Target"},{key:"method",label:"Method",placeholder:"Hose / drip / sprinkler"},{key:"durationMinutes",label:"Duration (minutes)",type:"number"},{key:"estimatedLitres",label:"Estimated litres",type:"number"},{key:"operator",label:"Operator"},{key:"notes",label:"Notes"}]},
 {type:"health",label:"Animal health",description:"Vaccination, deworming, treatment, injury and inspection.",icon:Tractor,fields:[{key:"animalOrFlock",label:"Animal / flock / batch"},{key:"eventType",label:"Event type"},{key:"treatment",label:"Treatment"},{key:"dosage",label:"Dosage"},{key:"cost",label:"Cost",type:"number"},{key:"followUpDate",label:"Follow-up",type:"date"},{key:"notes",label:"Notes"}]},
 {type:"crop_health",label:"Crop health",description:"Pest, disease and crop observations.",icon:Leaf,fields:[{key:"field",label:"Field"},{key:"crop",label:"Crop"},{key:"observation",label:"Observation"},{key:"pest",label:"Pest"},{key:"disease",label:"Disease"},{key:"severity",label:"Severity"},{key:"followUpDate",label:"Follow-up",type:"date"}]},
 {type:"sale",label:"Sales",description:"Sales automatically create finance income.",icon:CircleDollarSign,fields:[{key:"amount",label:"Amount",type:"number"},{key:"category",label:"Product/category"},{key:"quantity",label:"Quantity",type:"number"},{key:"unit",label:"Unit"},{key:"unitPrice",label:"Unit price",type:"number"},{key:"counterparty",label:"Customer"},{key:"paymentMethod",label:"Payment method"},{key:"notes",label:"Notes"}]},
 {type:"expense",label:"Expenses",description:"Expenses automatically create finance transactions.",icon:CircleDollarSign,fields:[{key:"amount",label:"Amount",type:"number"},{key:"category",label:"Category"},{key:"counterparty",label:"Supplier/payee"},{key:"paymentMethod",label:"Payment method"},{key:"reference",label:"Reference"},{key:"notes",label:"Notes"}]},
 {type:"equipment",label:"Equipment",description:"Pumps, hoses, tools, solar and farm assets.",icon:Wrench,fields:[{key:"assetId",label:"Asset ID"},{key:"category",label:"Category"},{key:"purchaseDate",label:"Purchase date",type:"date"},{key:"purchasePrice",label:"Purchase price",type:"number"},{key:"location",label:"Location"},{key:"condition",label:"Condition"},{key:"nextMaintenance",label:"Next maintenance",type:"date"},{key:"notes",label:"Notes"}]},
 {type:"compost",label:"Compost & manure",description:"Return livestock and crop residues to production.",icon:Wheat,fields:[{key:"source",label:"Source"},{key:"quantity",label:"Quantity",type:"number"},{key:"storageLocation",label:"Storage location"},{key:"intendedUse",label:"Intended use"},{key:"destination",label:"Destination"},{key:"notes",label:"Notes"}]},
 {type:"resource_transfer",label:"Resource transfers",description:"Track flows such as piggery → compost → garden.",icon:Wheat,fields:[{key:"source",label:"From"},{key:"destination",label:"To"},{key:"resource",label:"Resource"},{key:"quantity",label:"Quantity",type:"number"},{key:"unit",label:"Unit"},{key:"notes",label:"Notes"}]},
];

const api=(path:string)=>`${(import.meta.env.VITE_API_URL||"").replace(/\/$/,"")}${path}`;

export function FarmOperationsPage({defaultType}:{defaultType?:string}){
 const [activeType,setActiveType]=useState(defaultType||"pig"); const [records,setRecords]=useState<RecordItem[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(false); const [modal,setModal]=useState(false); const [saving,setSaving]=useState(false); const [message,setMessage]=useState("");
 const active=modules.find(m=>m.type===activeType)||modules[0];
 const load=async()=>{setLoading(true);setError(false);try{const r=await fetch(api(`/api/operations?type=${encodeURIComponent(active.type)}`));if(!r.ok)throw new Error();setRecords(await r.json());}catch{setError(true)}finally{setLoading(false)}};
 useEffect(()=>{void load()},[active.type]);
 const save=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setSaving(true);const f=new FormData(e.currentTarget);const data:Record<string,unknown>={};active.fields.forEach(field=>{const v=f.get(field.key);if(v!==null&&String(v).trim())data[field.key]=field.type==="number"?Number(v):String(v)});try{const r=await fetch(api("/api/operations"),{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({recordType:active.type,name:String(f.get("name")||active.label),status:String(f.get("status")||"Active"),farmUnit:String(f.get("farmUnit")||active.label),recordDate:String(f.get("recordDate")||"")||null,data})});if(!r.ok){const b=await r.json().catch(()=>({}));throw new Error(b.error||"Could not save record")};setModal(false);await load()}catch(err){setMessage(err instanceof Error?err.message:"Could not save record")}finally{setSaving(false)}};
 const remove=async(id:number)=>{if(!window.confirm("Delete this record?"))return;await fetch(api(`/api/operations/${id}`),{method:"DELETE"});await load()};
 return <div className="animate-rise space-y-5"><PageHeading eyebrow="Farm operations" title="Farm records" detail="Operational records for livestock, crops, water, gardens, orchard, health, finance and resources." action={<div className="flex gap-2"><Button variant="ghost" onClick={()=>void load()}><RefreshCw size={15}/>Refresh</Button><Button onClick={()=>setModal(true)}><Plus size={15}/>Add record</Button></div>}/>
  <Panel className="overflow-hidden"><div className="flex gap-2 overflow-x-auto border-b border-[hsl(var(--border))] p-3">{modules.map(m=>{const Icon=m.icon;return <button key={m.type} onClick={()=>setActiveType(m.type)} className={`flex shrink-0 items-center gap-2 rounded-xl px-3 py-2 text-[11px] font-semibold ${active.type===m.type?"bg-[hsl(var(--primary))] text-white":"bg-[hsl(var(--muted))]"}`}><Icon size={14}/>{m.label}</button>})}</div>
   <div className="p-4 sm:p-5"><div className="mb-5 flex items-end justify-between gap-4"><div><div className="font-mono text-[9px] uppercase tracking-[.16em] text-[hsl(var(--muted-foreground))]">Operating module</div><h2 className="mt-1 text-2xl font-bold">{active.label}</h2><p className="mt-1 text-sm text-[hsl(var(--muted-foreground))]">{active.description}</p></div><Button onClick={()=>setModal(true)}><Plus size={15}/>Add</Button></div>
    {loading?<Loading rows={4}/>:error?<ErrorState onRetry={()=>void load()}/>:records.length===0?<EmptyState title={`No ${active.label.toLowerCase()} records yet`} detail="Add the first record. The app does not invent farm history." onAdd={()=>setModal(true)}/>:<div className="space-y-2">{records.map(r=><div key={r.id} className="rounded-2xl border border-[hsl(var(--border))] p-4"><div className="flex justify-between gap-3"><div><h3 className="font-semibold">{r.name}</h3><div className="mt-1 text-[10px] text-[hsl(var(--muted-foreground))]">{r.farmUnit}{r.recordDate?` · ${r.recordDate}`:""} · {r.status}</div></div><button onClick={()=>void remove(r.id)} className="p-2 text-[hsl(var(--muted-foreground))]" aria-label="Delete"><Trash2 size={15}/></button></div><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{Object.entries(r.data||{}).filter(([k])=>k!=="financeId").slice(0,9).map(([k,v])=><div key={k} className="rounded-xl bg-[hsl(var(--muted)/.55)] p-2.5"><div className="text-[9px] uppercase text-[hsl(var(--muted-foreground))]">{k.replace(/[A-Z]/g,m=>` ${m}`)}</div><div className="mt-1 text-xs font-semibold">{String(v)}</div></div>)}</div></div>)}</div>}
   </div></Panel>
   <Panel className="p-4 sm:p-5"><PanelTitle eyebrow="Farm setup" title="Boroma Hills operating structure" action={<Button variant="ghost" onClick={async()=>{setMessage("");try{const r=await fetch(api("/api/operations/bootstrap"),{method:"POST"});const b=await r.json();setMessage(b.message||"Structure created");}catch{setMessage("Could not create structure")}}}>Create structure</Button>}/><p className="mt-3 text-sm text-[hsl(var(--muted-foreground))]">Creates the farm's non-financial operating structure without creating fake animal history or financial transactions.</p>{message&&<div className="mt-3 rounded-xl bg-[hsl(var(--muted))] p-3 text-xs">{message}</div>}</Panel>
   {modal&&<Modal title={`Add ${active.label}`} onClose={()=>setModal(false)}><form onSubmit={save} className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><label><span className="mb-1 block text-[11px] font-semibold">Name *</span><input name="name" required className="h-10 w-full rounded-xl border bg-transparent px-3 text-sm"/></label><SelectField label="Status" name="status" options={["Active","Planned","Completed","Sold","Deceased","Sick","Quarantine"]}/><label><span className="mb-1 block text-[11px] font-semibold">Farm unit</span><input name="farmUnit" defaultValue={active.label} className="h-10 w-full rounded-xl border bg-transparent px-3 text-sm"/></label><label><span className="mb-1 block text-[11px] font-semibold">Date</span><input name="recordDate" type="date" className="h-10 w-full rounded-xl border bg-transparent px-3 text-sm"/></label></div><div className="grid gap-4 sm:grid-cols-2">{active.fields.map(field=><label key={field.key}><span className="mb-1 block text-[11px] font-semibold">{field.label}</span><input name={field.key} type={field.type||"text"} placeholder={field.placeholder} min={field.type==="number"?"0":undefined} className="h-10 w-full rounded-xl border bg-transparent px-3 text-sm"/></label>)}</div><div className="flex justify-end gap-2 border-t pt-4"><Button variant="ghost" type="button" onClick={()=>setModal(false)}>Cancel</Button><Button type="submit" disabled={saving}>{saving?"Saving…":"Save record"}</Button></div></form></Modal>}
 </div>;
}
