import { useEffect, useState, type FormEvent } from "react";
import { Activity, History, Plus, RefreshCw, Scale, Trash2, X } from "lucide-react";
import { Button, EmptyState, ErrorState, Loading, Modal, Panel, PanelTitle, SelectField } from "@/components/ui-kit";
import { PageHeading } from "@/components/farm-shell";

type Pig = { id:number; name:string; status:string; farmUnit:string; recordDate:string|null; data:Record<string,unknown> };
type Event = { id:number; name:string; recordDate:string|null; data:Record<string,unknown> };
const api=(path:string)=>`${(import.meta.env.VITE_API_URL||"").replace(/\/$/,"")}${path}`;
const text=(v:unknown)=>v == null || v === "" ? "—" : String(v);

export default function PigManagementPage(){
 const [pigs,setPigs]=useState<Pig[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(false); const [modal,setModal]=useState(false); const [eventPig,setEventPig]=useState<Pig|null>(null); const [historyPig,setHistoryPig]=useState<Pig|null>(null); const [history,setHistory]=useState<Event[]>([]); const [saving,setSaving]=useState(false); const [message,setMessage]=useState("");
 const load=async()=>{setLoading(true);setError(false);try{const r=await fetch(api("/api/pig-management"));if(!r.ok)throw new Error();setPigs(await r.json())}catch{setError(true)}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setSaving(true);const f=new FormData(e.currentTarget);const data={pigId:String(f.get("pigId")||""),sex:String(f.get("sex")||""),breed:String(f.get("breed")||""),birthDate:String(f.get("birthDate")||""),weightKg:Number(f.get("weightKg")||0),pen:String(f.get("pen")||""),health:String(f.get("health")||"Good"),notes:String(f.get("notes")||"")};try{const r=await fetch(api("/api/pig-management"),{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:data.pigId,data,recordDate:data.birthDate||null})});if(!r.ok)throw new Error((await r.json()).error||"Could not save pig");setModal(false);await load()}catch(err){setMessage(err instanceof Error?err.message:"Could not save pig")}finally{setSaving(false)}};
 const saveEvent=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!eventPig)return;setSaving(true);const f=new FormData(e.currentTarget);const eventType=String(f.get("eventType"));const data={notes:String(f.get("notes")||""),weightKg:f.get("weightKg")?Number(f.get("weightKg")):undefined,quantityKg:f.get("quantityKg")?Number(f.get("quantityKg")):undefined,treatment:String(f.get("treatment")||""),amount:f.get("amount")?Number(f.get("amount")):undefined};try{const r=await fetch(api(`/api/pig-management/${eventPig.id}/events`),{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({eventType,data,recordDate:new Date().toISOString().slice(0,10)})});if(!r.ok)throw new Error((await r.json()).error||"Could not record event");setEventPig(null);await load()}catch(err){setMessage(err instanceof Error?err.message:"Could not record event")}finally{setSaving(false)}};
 const openHistory=async(pig:Pig)=>{setHistoryPig(pig);const r=await fetch(api(`/api/pig-management/${pig.id}/history`));setHistory(r.ok?await r.json():[])};
 const remove=async(pig:Pig)=>{if(!window.confirm(`Delete ${pig.name}? This removes the pig register record.`))return;const r=await fetch(api(`/api/pig-management/${pig.id}`),{method:"DELETE"});if(r.ok)await load()};
 return <div className="animate-rise space-y-5"><PageHeading eyebrow="Livestock · Pigs" title="Pig Management" detail="Register pigs, track growth and health, and keep a history of feed, breeding, mortality and sales." action={<div className="flex gap-2"><Button variant="ghost" onClick={()=>void load()}><RefreshCw size={15}/>Refresh</Button><Button onClick={()=>setModal(true)}><Plus size={15}/>Register pig</Button></div>}/>
  <Panel className="p-4 sm:p-5"><PanelTitle eyebrow="Piggery register" title={`${pigs.filter(p=>!['Sold','Deceased'].includes(p.status)).length} active pigs`} /><div className="mt-5">{loading?<Loading rows={4}/>:error?<ErrorState onRetry={()=>void load()}/>:pigs.length===0?<EmptyState title="No pigs registered" detail="Register the first pig when animals arrive. The app does not invent livestock." onAdd={()=>setModal(true)}/>:<div className="grid gap-3 lg:grid-cols-2">{pigs.map(p=><div key={p.id} className="rounded-2xl border border-[hsl(var(--border))] p-4"><div className="flex justify-between gap-3"><div><h3 className="font-semibold">{p.name}</h3><div className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">{text(p.data.breed)} · {text(p.data.sex)} · {text(p.data.pen)} · {p.status}</div></div><button onClick={()=>void remove(p)} aria-label="Delete pig" className="p-2 text-[hsl(var(--muted-foreground))]"><Trash2 size={15}/></button></div><div className="mt-4 grid grid-cols-2 gap-2 text-xs"><div className="rounded-xl bg-[hsl(var(--muted)/.55)] p-3"><Scale size={14}/><div className="mt-1 text-[9px] uppercase text-[hsl(var(--muted-foreground))]">Weight</div><b>{text(p.data.weightKg)} kg</b></div><div className="rounded-xl bg-[hsl(var(--muted)/.55)] p-3"><Activity size={14}/><div className="mt-1 text-[9px] uppercase text-[hsl(var(--muted-foreground))]">Health</div><b>{text(p.data.health)}</b></div></div><div className="mt-3 flex flex-wrap gap-2"><Button size="sm" variant="ghost" onClick={()=>setEventPig(p)}><Plus size={13}/>Event</Button><Button size="sm" variant="ghost" onClick={()=>void openHistory(p)}><History size={13}/>History</Button></div></div>)}</div>}</div></Panel>
  {modal&&<Modal title="Register pig" onClose={()=>setModal(false)}><form onSubmit={submit} className="space-y-3"><input name="pigId" required placeholder="Pig ID / name" className="w-full rounded-xl border p-3"/><div className="grid grid-cols-2 gap-3"><SelectField label="Sex" name="sex" options={[{value:"Female",label:"Female"},{value:"Male",label:"Male"}]} required/><input name="breed" placeholder="Breed" className="rounded-xl border p-3"/><input name="birthDate" type="date" className="rounded-xl border p-3"/><input name="weightKg" type="number" min="0" step="0.1" placeholder="Weight kg" className="rounded-xl border p-3"/><input name="pen" placeholder="Pen" className="rounded-xl border p-3"/><input name="health" placeholder="Health" defaultValue="Good" className="rounded-xl border p-3"/></div><textarea name="notes" placeholder="Notes" className="w-full rounded-xl border p-3"/><Button type="submit" disabled={saving}>{saving?"Saving…":"Register pig"}</Button></form></Modal>}
  {eventPig&&<Modal title={`Record event · ${eventPig.name}`} onClose={()=>setEventPig(null)}><form onSubmit={saveEvent} className="space-y-3"><SelectField label="Event" name="eventType" options={["health","weight","feed","mortality","breeding","farrowing","weaning","sale"].map(x=>({value:x,label:x}))} required/><input name="weightKg" type="number" min="0" step="0.1" placeholder="Weight kg (if applicable)" className="w-full rounded-xl border p-3"/><input name="quantityKg" type="number" min="0" step="0.1" placeholder="Feed kg (if applicable)" className="w-full rounded-xl border p-3"/><input name="treatment" placeholder="Treatment / medicine" className="w-full rounded-xl border p-3"/><input name="amount" type="number" min="0" step="0.01" placeholder="Sale amount (if applicable)" className="w-full rounded-xl border p-3"/><textarea name="notes" placeholder="Notes" className="w-full rounded-xl border p-3"/><Button type="submit" disabled={saving}>{saving?"Saving…":"Record event"}</Button></form></Modal>}
  {historyPig&&<Modal title={`History · ${historyPig.name}`} onClose={()=>setHistoryPig(null)}><div className="space-y-2">{history.length===0?<p className="text-sm text-[hsl(var(--muted-foreground))]">No events recorded yet.</p>:history.map(e=><div key={e.id} className="rounded-xl border p-3"><div className="flex justify-between"><b>{String(e.data.eventType)}</b><span className="text-xs text-[hsl(var(--muted-foreground))]">{text(e.recordDate)}</span></div><p className="mt-1 text-xs">{text(e.data.notes)}</p></div>)}</div></Modal>}
  {message&&<div className="fixed bottom-5 right-5 rounded-xl border bg-background p-3 text-xs shadow-lg"><button onClick={()=>setMessage("")} className="float-right"><X size={13}/></button>{message}</div>}
 </div>;
}
