import { Link } from 'wouter';
import { useAuth } from '@/lib/auth';
import { PageHeading } from '@/components/farm-shell';

const sectionCards:Record<string,{href:string;title:string;text:string}>={goats:{href:'/livestock/goats',title:'Goat unit',text:'Register, health, breeding, weights and mortality.'},poultry:{href:'/livestock/poultry',title:'Poultry unit',text:'Batches, feed, mortality, weights and production.'},pigs:{href:'/pigs',title:'Pig unit',text:'Pig register, health, feed, breeding and sales.'},fish:{href:'/fish',title:'Fish unit',text:'Stock, feeding, growth, harvest and water quality.'},crops:{href:'/crops',title:'Crops & garden',text:'Fields, planting, activities, health and harvest.'},water:{href:'/water',title:'Water & irrigation',text:'Tank levels, water usage and irrigation work.'},inventory:{href:'/inventory',title:'Inventory',text:'Inputs, feed, stock levels and movements.'}};

function PlatformDashboard() {
  const { user, farms } = useAuth();
  if (!user) return null;
  const active = farms.filter(f => f.status === 'active').length;
  const suspended = farms.filter(f => f.status === 'suspended').length;
  const other = farms.length - active - suspended;
  return <div className="space-y-7">
    <PageHeading eyebrow="Camluk Platform" title={`Good day, ${user.displayName}`} detail="Manage the Camluk Farm OS platform, onboard farm tenants and switch into a farm workspace when needed." action={<Link href="/platform/farms" className="rounded-xl bg-[hsl(var(--primary))] px-4 py-2.5 text-sm font-semibold text-[hsl(var(--primary-foreground))]">Onboard a farm</Link>} />
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
      {[['Total farms', farms.length, 'Registered farm tenants'],['Active farms', active, 'Currently active tenants'],['Suspended farms', suspended, 'Tenants needing attention'],['Other status', other, 'Pending or other lifecycle state']].map(([label,value,text]) => <div key={String(label)} className="rounded-2xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-5 shadow-sm"><div className="font-mono text-[9px] uppercase tracking-[.18em] text-[hsl(var(--muted-foreground))]">{label}</div><div className="mt-2 text-3xl font-bold tracking-tight">{value}</div><div className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">{text}</div></div>)}
    </div>
    <div className="grid gap-5 lg:grid-cols-[1.15fr_.85fr]">
      <section className="rounded-2xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-5 shadow-sm"><div className="flex items-center justify-between gap-3"><div><h2 className="font-semibold">Farm tenants</h2><p className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">Your current platform tenant list.</p></div><Link href="/platform/farms" className="text-xs font-semibold text-[hsl(var(--primary))]">Manage farms →</Link></div><div className="mt-4 space-y-2">{farms.slice(0,6).map(f => <div key={f.id} className="flex items-center justify-between rounded-xl border p-3"><div><div className="text-sm font-medium">{f.name}</div><div className="mt-0.5 font-mono text-[9px] text-[hsl(var(--muted-foreground))]">{f.id}</div></div><span className={`rounded-full px-2.5 py-1 text-[10px] font-semibold ${f.status === 'active' ? 'bg-green-100 text-green-800 dark:bg-green-950/40 dark:text-green-300' : f.status === 'suspended' ? 'bg-red-100 text-red-800 dark:bg-red-950/40 dark:text-red-300' : 'bg-yellow-100 text-yellow-800 dark:bg-yellow-950/40 dark:text-yellow-300'}`}>{f.status}</span></div>)}{!farms.length && <div className="rounded-xl border border-dashed p-6 text-center text-sm text-[hsl(var(--muted-foreground))]">No farm tenants have been onboarded yet.</div>}</div></section>
      <section className="rounded-2xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-5 shadow-sm"><h2 className="font-semibold">Platform actions</h2><div className="mt-4 space-y-2"><Link href="/platform/farms" className="block rounded-xl border p-4 transition hover:bg-[hsl(var(--muted)/.35)]"><div className="text-sm font-semibold">Farm onboarding</div><p className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">Create a tenant and its first owner administrator.</p></Link>{user.activeFarmId && <Link href="/home" className="block rounded-xl border p-4 transition hover:bg-[hsl(var(--muted)/.35)]"><div className="text-sm font-semibold">Open active farm</div><p className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">Enter the operational workspace for {user.activeFarmName}.</p></Link>}<Link href="/users" className="block rounded-xl border p-4 transition hover:bg-[hsl(var(--muted)/.35)]"><div className="text-sm font-semibold">Users & access</div><p className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">Manage access for the currently selected farm.</p></Link></div></section>
    </div>
  </div>;
}

export default function RoleDashboardPage(){const{user}=useAuth();if(!user)return null;if(user.role==='platform_admin')return <PlatformDashboard/>;const management=['owner_admin','farm_manager','farm_supervisor'].includes(user.role);const cards=management?Object.values(sectionCards):user.sections.map(k=>sectionCards[k]).filter(Boolean);return <div><PageHeading eyebrow={user.roleName} title={`Good day, ${user.displayName}`} detail={management?'Your farm operations dashboard.':'Your assigned farm sections and daily work.'}/><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{cards.map(card=><Link key={card.href} href={card.href} className="rounded-2xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className="text-base font-semibold">{card.title}</div><p className="mt-2 text-sm text-[hsl(var(--muted-foreground))]">{card.text}</p></Link>)}<Link href="/today" className="rounded-2xl border p-5"><div className="font-semibold">Today's work</div><p className="mt-2 text-sm text-[hsl(var(--muted-foreground))]">See daily tasks and operational work.</p></Link>{management&&<Link href="/alerts" className="rounded-2xl border p-5"><div className="font-semibold">Farm alerts</div><p className="mt-2 text-sm text-[hsl(var(--muted-foreground))]">Review health, stock and operational warnings.</p></Link>}{user.permissions.includes('finance.view')&&<Link href="/finance" className="rounded-2xl border p-5"><div className="font-semibold">Finance</div><p className="mt-2 text-sm text-[hsl(var(--muted-foreground))]">Review income, expenses and performance.</p></Link>}{user.permissions.includes('users.manage')&&<Link href="/users" className="rounded-2xl border p-5"><div className="font-semibold">User management</div><p className="mt-2 text-sm text-[hsl(var(--muted-foreground))]">Create users and assign roles and sections.</p></Link>}</div></div>}
