import { Router } from "express";
import { eq } from "drizzle-orm";
import { db, authPermissions, authRolePermissions, authRoles } from "@workspace/db";
import { requireAuth } from "./auth";

const router=Router();
const ROLE_PERMISSION_KEYS:Record<string,string[]>={owner_admin:["dashboard.view","farm.view","farm.edit","farm.delete","finance.view","finance.edit","users.manage","settings.manage","reports.view"],farm_manager:["dashboard.view","farm.view","farm.edit","farm.delete","finance.view","finance.edit","reports.view"],farm_supervisor:["dashboard.view","farm.view","farm.edit","reports.view"],section_head:["dashboard.view","farm.view","farm.edit"],field_worker:["dashboard.view","farm.view","farm.edit"]};
export async function ensureRolePermissions(req:any,res:any,next:any){try{const role=(await db.select().from(authRoles).where(eq(authRoles.key,req.authUser.role)).limit(1))[0];if(!role)return res.status(400).json({message:'Role not found'});const keys=ROLE_PERMISSION_KEYS[role.key]||ROLE_PERMISSION_KEYS.field_worker;const permissions=await db.select().from(authPermissions);for(const permission of permissions.filter(p=>keys.includes(p.key)))await db.insert(authRolePermissions).values({roleId:role.id,permissionId:permission.id}).onConflictDoNothing();return next()}catch(error){return next(error)}}
router.post('/auth/ensure-permissions',requireAuth,async(req,res,next)=>{try{await ensureRolePermissions(req,res,()=>{});return res.json({ok:true})}catch(error){return next(error)}});
export function requireFarmSectionAccess(req:any,res:any,next:any){const user=req.authUser;if(!user)return res.status(401).json({message:'Authentication required'});if(['owner_admin','farm_manager','farm_supervisor'].includes(user.role))return next();const path=req.path;let section:string|undefined;if(path.includes('goat'))section='goats';else if(path.includes('poultry'))section='poultry';else if(path.includes('pig'))section='pigs';else if(path.includes('fish'))section='fish';else if(path.includes('crop')||path.includes('garden')||path.includes('orchard')||path.includes('greenhouse')||path.includes('field'))section='crops';else if(path.includes('water')||path.includes('irrigation'))section='water';else if(path.includes('inventory'))section='inventory';if(path.includes('finance')||path.includes('expenses')||path.includes('sales'))return user.permissions.includes('finance.view')?next():res.status(403).json({message:'Finance access denied'});if(path.includes('users'))return user.permissions.includes('users.manage')?next():res.status(403).json({message:'User administration access denied'});if(section&&!user.sections.includes(section))return res.status(403).json({message:`Access denied for section: ${section}`});return next()}
export default router;
