import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter, { requireAuth } from "./auth";
import authPermissionsRouter, { requireFarmSectionAccess } from "./auth-permissions";
import farmOverridesRouter from "./farm-overrides";
import farmRouter from "./farm";
import farmManagementRouter from "./farm-management";
import operationsRouter from "./operations";
import demoRouter from "./demo";
import goatManagementRouter from "./goat-management";
import poultryManagementRouter from "./poultry-management";
import pigManagementRouter from "./pig-management";
import { requireActiveFarmContext } from "../lib/farm-context";

const router: IRouter = Router();
router.use(healthRouter);
router.use(authRouter);
router.use(authPermissionsRouter);
router.use(requireAuth);
router.use(requireFarmSectionAccess);
router.use(requireActiveFarmContext);
router.use(farmManagementRouter);
router.use(farmOverridesRouter);
router.use(farmRouter);
router.use(operationsRouter);
router.use(goatManagementRouter);
router.use(poultryManagementRouter);
router.use(pigManagementRouter);
router.use(demoRouter);
export default router;
